import streamlit as st
from fishki import data_store

st.set_page_config(page_title="Fishki — German Flashcards", page_icon="🐟", layout="wide")

# Initialize data from CSV files into session state
if 'decks_df' not in st.session_state or 'cards_df' not in st.session_state:
    st.session_state.decks_df, st.session_state.cards_df = data_store.load_data()

st.title("🐟 Fishki — German Flashcards")
st.sidebar.header("Navigation")

# The page links are automatically generated by streamlit from the pages folder.
# We just need to provide a welcome message.

st.write("Welcome to Fishki!")
st.write("Use the sidebar to navigate. Create a deck in **Decks** to get started.")
