import streamlit as st
from fishki import data_store, ui

st.set_page_config(page_title="Fishki — German Flashcards", page_icon="🐟", layout="wide")

# Initialize data from CSV files into session state
if 'decks_df' not in st.session_state or 'cards_df' not in st.session_state or 'saved_words_df' not in st.session_state:
    st.session_state.decks_df, st.session_state.cards_df, st.session_state.saved_words_df = data_store.load_data()

st.title("🐟 Fishki — German Flashcards")
st.sidebar.header("Navigation")

# Quick save widget in sidebar
st.sidebar.subheader("💾 Quick Save Word")
ui.save_word_widget()

st.sidebar.write("---")

# The page links are automatically generated by streamlit from the pages folder.
# We just need to provide a welcome message.

st.write("Welcome to Fishki!")
st.write("Use the sidebar to navigate. Create a deck in **Decks** to get started.")

# Show some saved words stats if available
if not st.session_state.saved_words_df.empty:
    total_saved = len(st.session_state.saved_words_df)
    not_reviewed = len(st.session_state.saved_words_df[st.session_state.saved_words_df["reviewed"] == False])
    
    st.info(f"📚 You have {total_saved} saved words ({not_reviewed} not reviewed yet). Visit the **Saved Words** page to review them!")
